apiVersion: v1
kind: Secret
metadata:
  name: cost-optimizer-secrets
  namespace: default
type: Opaque
data:
  # Value: postgres
  database-password: cG9zdGdyZXM=
  # Value: U29tZVN1cGVyU2VjcmV0S2V5Rm9ySjg4c0Nvc3RPcHRpbWl6ZXJXaGljaElzU3Ryb25nRW5vdWdoT3V0c3RhbmRpbmdseVNlY3VyZQ==
  jwt-secret: VTI5dGVWTjFjR1Z5VTJWeGNtVjBTMlY1Um05eVNqZzRjR052YzNScGNtbHpaWEpYYUdsemFXTlpieTFTZEhKdmJtZHNlVk5sWTNWeVpRPT0=
